### ISSUE TITLE
Yanked Bindgen

### ISSUE THREAD

**Issue by Luxrod** [amatho/mupen64plus-input-gca#1]
Hi! I was wanting to use your .zip to fix my issues with setting up the gamecube adapter to work with mupen64plus but it will not let me initiate the build process due to version 0.54.1 being removed:

E:\Program Files\mupen64plus>cargo build
    Updating crates.io index
error: failed to select a version for the requirement `bindgen = "^0.54.1"`
candidate versions found which didn't match: 0.57.0, 0.56.0, 0.55.1, ...
location searched: crates.io index
required by package `mupen64plus-input-gca v0.1.0 (E:\Program Files\mupen64plus)`

Can you help?

**Comment by amatho** [comment]
Fixed in #2
