### ISSUE TITLE
Config file location

### ISSUE THREAD

**Issue by Rosalie241** [amatho/mupen64plus-input-gca#10]
Could you please put the config file in the user config directory location, it's the proper location for it, I'd open a PR but I'm unfamiliar with rust.

If it was a plugin written in C I'd do something like
```c
char path[PATH_MAX] = {0};
strcpy(path, ConfigGetUserConfigPath());
#ifdef _WIN32
strcat(path, "\\");
#else
strcat(path, "/");
#endif // _WIN32
strcat(path, "mupen64plus-input-gca.toml");
```

see <http://mupen64plus.org/wiki/index.php?title=Mupen64Plus_v2.0_Core_Config> (the `ConfigGetUserConfigPath` function)

**Comment by amatho** [comment]
Sorry for the late answer! I'll look into this when I have the time, the way it's currently implemented was meant to be a temporary solution but I never fixed it :P
