### ISSUE TITLE
Allow the adapter to be connected after plugin startup

### ISSUE THREAD

**Issue by GhostlyDark** [amatho/mupen64plus-input-gca#11]
It would be nice if the emulator didn't crash when trying to use the plugin without an adapter being connected.

```
Input Error: Could not connect to GameCube adapter
Input Error: Could not start adapter read thread
UI-Console Error: Error: Input plugin library '.\mupen64plus-input-gca.dll' failed to start.
UI-Console Error: Specified Input plugin not found: mupen64plus-input-gca
```

**Comment by amatho** [comment]
I'll see if I can find a solution. Maybe I can continuously try to open the adapter every second or something.

**Comment by amatho** [comment]
I was a bit late with fixing this issue... 😅
