### ISSUE TITLE
M64Py "Failed to load dynlib/dll"

### ISSUE THREAD

**Issue by LoryT20** [amatho/mupen64plus-input-gca#15]
Hello, I'm using M64Py version 0.2.5. I installed the plugin, but it doesn't seem to show up in the input drop down list. I checked the log viewer, and noticed this error message related to it.

Frontend: ERROR: failed to load plugin C:\Program Files (x86)\M64Py\mupen64plus-input-gca.dll: Failed to load dynlib/dll 'C:\\Program Files (x86)\\M64Py\\mupen64plus-input-gca.dll'. Most probably this dynlib/dll was not found when the application was frozen.

This seems to be the case for both the compact and regular version of the plugin. This very well may be an issue on my end, but any help would be appreciated.

**Comment by GhostlyDark** [comment]
This plugin is 64-bit, while m64py is 32-bit. It simply won't run with it.

You'll need to use a launcher/frontend that is running 64-bit mupen64plus.
https://github.com/GhostlyDark/EMG
https://github.com/Rosalie241/RMG

**Comment by LoryT20** [comment]
Thanks for the response! I switched to simple64 and it worked great.
