### ISSUE TITLE
Not working on latest April 2021 m64p build

### ISSUE THREAD

**Issue by Fivavoa** [amatho/mupen64plus-input-gca#4]
Even while changing the input, I get no detection whatsoever.

**Comment by amatho** [comment]
Hmm, there seems to be a breaking change in mupen64plus' handling of input plugins, I'll see if I can figure out the issue.

**Comment by amatho** [comment]
Should be fixed in the newest release!

**Comment by Fivavoa** [comment]
That was a surprisingly fast response considering the age of the last update! Thank you so much!
