### ISSUE TITLE
Menu acts like control stick is being held down

### ISSUE THREAD

**Issue by Littletiger** [amatho/mupen64plus-input-gca#8]
On F-Zero x and Diddy Kong Racing(and maybe others) the main menu acts as if the control stick is being held down on the controller.

If you unplug the grey USB and only use the black USB it works as expected.

I have tested this on the latest m64p with the 0.5.0 compat plugin on Windows and Linux.

**Comment by amatho** [comment]
Hmm, this sounds like the deadzone is too low. Could you try to increase it in the configuration file?

**Comment by Littletiger** [comment]
Changing the deadzone doesn't make a difference, to clarify the adapter does work fine with both USBs in game, it's just the menus on those 2 games where the issue occurs.

Games like Mario 64 and Banjo Kazooie work everywhere.

**Comment by amatho** [comment]
Oh ok, sounds like a strange bug! I'll look into it when I have time.

**Comment by Littletiger** [comment]
0.5.1 seems to have fixed whatever was causing the issue

**Comment by amatho** [comment]
Oh, nice!
